res = {
    "data": [{
        "sub": "nlp",
        "auth_id": "bf1b10dbf47f19d14a49a167693b76cd",
        "intent": {
            "answer": {
                "text": "上海明天全天大雨转小雨，出门记得带伞，气温22℃ ~ 25℃，空气质量良，有东北风转北风3-4级，温度适宜。",
                "type": "T"
            },
            "data": {
                "result": [{
                    "airData": 45,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-12",
                    "dateLong": 1562860800,
                    "date_for_voice": "今天",
                    "exp": {
                        "ct": {
                            "expName": "穿衣指数",
                            "level": "热",
                            "prompt": "天气较热，衣物精干简洁，室内酌情添加空调衫。"
                        },
                        "dy": {
                            "expName": "钓鱼指数",
                            "level": "较适宜",
                            "prompt": "下雨天最考验用竿用饵的技巧。"
                        },
                        "gm": {
                            "expName": "感冒指数",
                            "level": "较易发",
                            "prompt": "感冒较易发生，干净整洁的环境和清新流通的空气都有利于降低感冒的几率，体质较弱的童鞋们要特别加强自我保护。"
                        },
                        "jt": {
                            "expName": "交通指数",
                            "level": "一般",
                            "prompt": "有较强降水，路面湿滑，刹车距离延长，事故易发期，注意车距，务必小心驾驶。"
                        },
                        "tr": {
                            "expName": "旅游指数",
                            "level": "一般",
                            "prompt": "温度适宜，但风稍大，且较强降雨的天气将给您的出行带来很多的不便，若坚持旅行建议带上雨具。"
                        },
                        "uv": {
                            "expName": "紫外线指数",
                            "level": "最弱",
                            "prompt": "辐射弱，涂擦SPF8-12防晒护肤品。"
                        },
                        "xc": {
                            "expName": "洗车指数",
                            "level": "不宜",
                            "prompt": "雨(雪)水和泥水会弄脏您的爱车，不适宜清洗车辆。"
                        },
                        "yd": {
                            "expName": "运动指数",
                            "level": "适宜",
                            "prompt": "天气较好，且紫外线辐射不强，适宜户外运动。"
                        }
                    },
                    "humidity": "87%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/01.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "pm25": "44",
                    "precipitation": "0",
                    "temp": 26,
                    "tempHigh": "28℃",
                    "tempLow": "22℃",
                    "tempRange": "22℃ ~ 28℃",
                    "tempReal": "27℃",
                    "warning": "",
                    "weather": "多云",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherDescription3": "22℃到29℃，风不大，温度适宜。",
                    "weatherDescription7": "22℃到31℃，风不大，有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 1,
                    "week": "周五",
                    "wind": "微风微风",
                    "windLevel": 0
                }, {
                    "airData": 46,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-11",
                    "dateLong": 1562774400,
                    "date_for_voice": "昨天",
                    "humidity": "82%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/07.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "28℃",
                    "tempLow": "22℃",
                    "tempRange": "22℃ ~ 28℃",
                    "weather": "小雨转多云",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 7,
                    "week": "周四",
                    "wind": "东南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": 51,
                    "airQuality": "良",
                    "city": "上海市",
                    "date": "2019-07-13",
                    "dateLong": 1562947200,
                    "date_for_voice": "明天",
                    "humidity": "92%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/09.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "25℃",
                    "tempLow": "22℃",
                    "tempRange": "22℃ ~ 25℃",
                    "weather": "大雨转小雨",
                    "weatherDescription": "温度适宜。",
                    "weatherType": 9,
                    "week": "周六",
                    "wind": "东北风转北风3-4级",
                    "windLevel": 1
                }, {
                    "airData": 48,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-14",
                    "dateLong": 1563033600,
                    "date_for_voice": "后天",
                    "humidity": "91%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/01.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "29℃",
                    "tempLow": "22℃",
                    "tempRange": "22℃ ~ 29℃",
                    "weather": "多云",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 1,
                    "week": "周日",
                    "wind": "东北风转东南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": 48,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-15",
                    "dateLong": 1563120000,
                    "date_for_voice": "15号",
                    "humidity": "90%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/07.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "28℃",
                    "tempLow": "23℃",
                    "tempRange": "23℃ ~ 28℃",
                    "weather": "小雨转大雨",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 7,
                    "week": "下周一",
                    "wind": "东南风4-5级",
                    "windLevel": 2
                }, {
                    "airData": 43,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-16",
                    "dateLong": 1563206400,
                    "date_for_voice": "16号",
                    "humidity": "86%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/07.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "31℃",
                    "tempLow": "26℃",
                    "tempRange": "26℃ ~ 31℃",
                    "weather": "小雨",
                    "weatherDescription": "气温较高，请尽量避免午后高温时段的户外活动。",
                    "weatherType": 7,
                    "week": "下周二",
                    "wind": "西南风转南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": 41,
                    "airQuality": "优",
                    "city": "上海市",
                    "date": "2019-07-17",
                    "dateLong": 1563292800,
                    "date_for_voice": "17号",
                    "humidity": "88%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/07.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "31℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 31℃",
                    "weather": "小雨",
                    "weatherDescription": "气温较高，请尽量避免午后高温时段的户外活动。",
                    "weatherType": 7,
                    "week": "下周三",
                    "wind": "西南风转东北风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-18",
                    "dateLong": 1563379200,
                    "date_for_voice": "18号",
                    "humidity": "87%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/07.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "28℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 28℃",
                    "weather": "小雨转多云",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 7,
                    "week": "下周四",
                    "wind": "东风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-19",
                    "dateLong": 1563465600,
                    "date_for_voice": "19号",
                    "humidity": "86%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "29℃",
                    "tempLow": "25℃",
                    "tempRange": "25℃ ~ 29℃",
                    "weather": "雨",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下周五",
                    "wind": "东风转东南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-20",
                    "dateLong": 1563552000,
                    "date_for_voice": "20号",
                    "humidity": "80%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "29℃",
                    "tempLow": "25℃",
                    "tempRange": "25℃ ~ 29℃",
                    "weather": "雨",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下周六",
                    "wind": "东南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-21",
                    "dateLong": 1563638400,
                    "date_for_voice": "21号",
                    "humidity": "80%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "29℃",
                    "tempLow": "26℃",
                    "tempRange": "26℃ ~ 29℃",
                    "weather": "雨转阴",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下周日",
                    "wind": "东南风转东北风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-22",
                    "dateLong": 1563724800,
                    "date_for_voice": "22号",
                    "humidity": "83%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "28℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 28℃",
                    "weather": "雨转阴",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下下周一",
                    "wind": "东北风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-23",
                    "dateLong": 1563811200,
                    "date_for_voice": "23号",
                    "humidity": "86%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "29℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 29℃",
                    "weather": "雨转晴",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下下周二",
                    "wind": "东风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-24",
                    "dateLong": 1563897600,
                    "date_for_voice": "24号",
                    "humidity": "87%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/01.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "30℃",
                    "tempLow": "23℃",
                    "tempRange": "23℃ ~ 30℃",
                    "weather": "多云转雨",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 1,
                    "week": "下下周三",
                    "wind": "东风转东南风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-25",
                    "dateLong": 1563984000,
                    "date_for_voice": "25号",
                    "humidity": "83%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "30℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 30℃",
                    "weather": "雨",
                    "weatherDescription": "有点热，适合穿短袖短裙等夏季清凉衣物。",
                    "weatherType": 8,
                    "week": "下下周四",
                    "wind": "东风3-4级",
                    "windLevel": 1
                }, {
                    "airData": -1,
                    "airQuality": "未知",
                    "city": "上海市",
                    "date": "2019-07-26",
                    "dateLong": 1564070400,
                    "date_for_voice": "26号",
                    "humidity": "84%",
                    "img": "http://aiui-res.ufile.ucloud.com.cn/weather/08.png",
                    "lastUpdateTime": "2019-07-12 09:55:08",
                    "tempHigh": "27℃",
                    "tempLow": "24℃",
                    "tempRange": "24℃ ~ 27℃",
                    "weather": "雨",
                    "weatherDescription": "温度适宜。",
                    "weatherType": 8,
                    "week": "下下周五",
                    "wind": "东风转东北风4-5级",
                    "windLevel": 2
                }]
            },
            "dialog_stat": "DataValid",
            "rc": 0,
            "save_history": true,
            "semantic": [{
                "intent": "QUERY",
                "slots": [{
                    "name": "datetime",
                    "normValue": "{\"datetime\":\"2019-07-13\",\"suggestDatetime\":\"2019-07-13\"}",
                    "value": "明天"
                }, {
                    "name": "location.city",
                    "normValue": "上海市",
                    "value": "上海市"
                }, {
                    "name": "location.cityAddr",
                    "normValue": "上海",
                    "value": "上海"
                }, {
                    "name": "location.type",
                    "normValue": "LOC_BASIC",
                    "value": "LOC_BASIC"
                }, {
                    "name": "queryType",
                    "value": "内容"
                }, {
                    "name": "subfocus",
                    "value": "天气状态"
                }]
            }],
            "service": "weather",
            "sid": "atn06faa360@dx000710834153a11101",
            "state": {
                "fg::weather::default::default": {
                    "state": "default"
                }
            },
            "text": "上海天气",
            "uuid": "atn06faa360@dx000710834153a11101"
        },
        "result_id": 1
    }],
    "sid": "ara0556908f@dx000110834153000100",
    "code": "0",
    "desc": "success"
}